Thêm hành chính controller
DeadlineShooters/Ads-Management pull request #61
Opened 2023-12-20 14:42 UTC by nmthong226

+ Duyệt danh sách yêu cầu cấp phép
+ Xem yêu cầu cấp phép
+ Duyệt yêu cầu

+ Duyệt danh sách chỉnh sửa bảng quảng cáo
+ Xem yêu cầu chỉnh bảng qc
+ Duyệt yêu cầu

2023-12-27 14:51 UTC, ItsMeNozo commented on models/adBoard.js
change adBoard to AdBoard because it's a model

2023-12-27 15:19 UTC, nmthong226 commented on models/adBoard.js
done

2023-12-27 15:19 UTC, ItsMeNozo requested changes

2023-12-27 15:19 UTC, ItsMeNozo commented on models/adBoardRequest.js
+ change all adBoard to AdBoard
+ ko có adImage do adImage là nằm trong adBoard rồi

2023-12-27 15:19 UTC, ItsMeNozo commented on models/adLocationChangeRequest.js
+ change all adBoard to AdBoard
+ lấy AdBoardChangeRequest do kiệt đổi tên lại rồi

2023-12-28 00:37 UTC, ItsMeNozo commented on models/adBoardRequest.js
file này chưa thấy thay đổi. Nhớ đổi adBoard: {type: Schema.Types.ObjectId, ref: "adBoard"}, thành adBoard: {type: Schema.Types.ObjectId, ref: "AdBoard"},

2023-12-28 15:35 UTC, ItsMeNozo approved these changes

2023-12-28 15:35 UTC, merged