Ad 70
DeadlineShooters/Ads-Management pull request #63
Opened 2023-12-25 12:58 UTC by 999Kit

did many things, please view commits to learn more

2023-12-25 15:58 UTC, ItsMeNozo commented
1. Sao mới vô sidebar giờ mất tiu cái hiện xanh dương rồi. Ví dụ mới vô là hiển thị trang chủ thì phải highlight xanh dương bên sidebar chứ. 
2. Sao sidebar bên quận phường giờ nhìn kì v. Width ko hợp lý  
![image](https://github.com/DeadlineShooters/Ads-Management/assets/91927045/ee9cf597-0d94-4116-b22b-f59517732a7d)

3. Chữ quên mật khẩu nằm ở đây hơi kỳ kỳ
![image](https://github.com/DeadlineShooters/Ads-Management/assets/91927045/edb3db05-ae46-4592-b0ea-06c9ac4b7912)

4. Để send mail thì ông có thể bắt chước bên tui: 
`// Configure Nodemailer
const transporter = nodemailer.createTransport({
  service: process.env.MAILER_SERVICE,
  secure: true,
  auth: {
    user: process.env.MAILER_USER,
    pass: process.env.MAILER_PASS,
  },
});
`

Rồi trong hàm controller: 
`  // send email:
  const emailOptions = await transporter.sendMail({
    from: "ngocphamanh2003@gmail.com", // Replace with your email
    to: foundReport.email, // Use the email from the foundReport
    subject: "Report Status Update",
    text: `Dear ${foundReport.fullName},\n\nYour report status has been updated to "${status}".\nHandling Procedure: ${method}\n\nBest regards,\nAds Management System`,
  });

  console.log("Message sent: %s", emailOptions.messageId);
`
Thêm này trong .env: 
```
MAILER_PASS="mgoo tfjv badn yclb"
MAILER_SERVICE=gmail
MAILER_USER=ngocphamanh2003@gmail.com
```

2023-12-25 16:04 UTC, ItsMeNozo reviewed
ủa sao test một hồi ko log in được với: 
Email: so@gmail.com
pass: letmein

2023-12-29 06:47 UTC, ItsMeNozo commented on models/user.js
bỏ Date.now()

2023-12-29 07:02 UTC, ItsMeNozo requested changes

2023-12-29 07:02 UTC, ItsMeNozo commented on controllers/dan.js
Thêm dòng này vào đầu của hàm controller.home để hiển thị active bên sidebar
  `res.locals.currentPage = "trang-chu";`

2023-12-29 08:27 UTC, 999Kit commented on controllers/dan.js
done nha

2023-12-29 08:42 UTC, ItsMeNozo approved these changes

2023-12-29 08:42 UTC, merged