Reset password
DeadlineShooters/Ads-Management pull request #64
Opened 2023-12-27 15:23 UTC by liwjln

Mọi người có thể đổi ngược điều kiện để gửi về mail bản thân (không phải user)
<img width="313" alt="image" src="https://github.com/DeadlineShooters/Ads-Management/assets/103946556/84de9065-30a9-44f8-a380-f90b244602b5"> (controllers -> auth.js -> controller.forgotPassword)
hoặc gửi về mail có trong db (user) và lấy otp code ở phần console

2023-12-28 01:00 UTC, ItsMeNozo commented on models/user.js
- Ngay datecreated bỏ default: Date.now() nha

2023-12-28 01:16 UTC, ItsMeNozo commented on views/so/quanLy/bangqc/edit.ejs
Cần kiểm tra lại file này khi merge thử vô main

2023-12-28 01:17 UTC, ItsMeNozo requested changes
xử lý cái comment của tui nha @liwjln. Mà thấy gửi ngược về mình nếu mail user ko tồn tại sao sao á :>

2023-12-28 02:34 UTC, liwjln commented on views/so/quanLy/bangqc/edit.ejs
Này tui làm tiếp từ branch của Kiệt nên khi nào branch Kiệt ok thì tui fix một lần luôn nha.

2023-12-30 08:06 UTC, ItsMeNozo approved these changes

2023-12-30 08:06 UTC, merged